In [1]:
import os
import math
import argparse
from tensorflow_asr.utils import env_util
#libraries
import os
import pandas as pd
import numpy as np
from keras import layers, models, optimizers
from keras import backend as K
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential, Model
from keras.layers import Input, Dense, Embedding, Conv2D, MaxPooling2D, Dropout,concatenate
from keras.layers import Dense, Flatten,Input, LSTM, Conv2D, MaxPooling1D, Dropout, Activation, Bidirectional,Dense, Input, Embedding, Dropout,SpatialDropout1D
from keras.optimizers import Adam
from keras.layers.embeddings import Embedding
from keras.callbacks import Callback, EarlyStopping, ModelCheckpoint
from keras.engine import Layer
from keras.layers import Activation, Add, Bidirectional, Conv1D, Dense, Dropout, Embedding, Flatten
from keras.layers import concatenate, GRU, Input, LSTM, MaxPooling1D
from keras.layers import GlobalAveragePooling1D,  GlobalMaxPooling1D, SpatialDropout1D
from keras.models import Model
from keras.optimizers import Adam
from keras.preprocessing import text, sequence
from sklearn.metrics import accuracy_score, roc_auc_score, log_loss
from sklearn.model_selection import train_test_split
from keras import initializers, regularizers, constraints, optimizers, layers, callbacks
from keras.utils import to_categorical
import matplotlib.pyplot as plt
#from utils import combine_images
from keras.layers.core import Reshape, Flatten
from PIL import Image
#from capsulelayers import CapsuleLayer, PrimaryCap, Length, Mask
from keras.layers.normalization import BatchNormalization

env_util.setup_environment()
import tensorflow as tf

DEFAULT_YAML = "/Users/vaibhavsingh/Desktop/TensorFlowASR/examples/contextnet/configs_local/config_macbook.yml"

import math
import os

from tensorflow_asr.landescapeviz import visualizer
from tensorflow_asr.landescapeviz import utils
from tensorflow_asr.landescapeviz import trajectory
from tensorflow_asr.configs.config import Config
from tensorflow_asr.datasets.asr_dataset import ASRTFRecordDataset, ASRSliceDataset
from tensorflow_asr.featurizers.speech_featurizers import TFSpeechFeaturizer
from tensorflow_asr.featurizers.text_featurizers import SubwordFeaturizer, SentencePieceFeaturizer, CharFeaturizer
from tensorflow_asr.models.transducer.contextnet import ContextNet
from tensorflow_asr.utils import app_util
from tensorflow_asr.optimizers.schedules import TransformerSchedule
from tqdm import tqdm
import argparse
from tensorflow_asr.utils import env_util, file_util

env_util.setup_environment()
import tensorflow as tf
tf.keras.backend.clear_session()
tf.config.optimizer.set_experimental_options({"auto_mixed_precision": False})
strategy = env_util.setup_strategy([0])

config = Config(DEFAULT_YAML)
speech_featurizer = TFSpeechFeaturizer(config.speech_config)

Use RNNT loss in TensorFlow


In [2]:
text_featurizer = CharFeaturizer(config.decoder_config)
tf.random.set_seed(0)

test_dataset = ASRSliceDataset(
        speech_featurizer=speech_featurizer,
        text_featurizer=text_featurizer,
        **vars(config.learning_config.test_dataset_config)
    )


In [3]:
batch_size = config.learning_config.running_config.batch_size

contextnet = ContextNet(**config.model_config, vocabulary_size=text_featurizer.num_classes)
contextnet.make(speech_featurizer.shape)
#TODO= contextnext.add(lambda layer)
#input = out of contextnext 
#out = tf.l2norm 
contextnet.load_weights("/Users/vaibhavsingh/Desktop/TensorFlowASR/examples/contextnet/models/model_lr_trained_05.h5", by_name=True)  


================INSIDE TRANSDUCER=================
before going to the encoder================= {'inputs': <tf.Tensor 'Placeholder:0' shape=(None, None, 80, 1) dtype=float32>, 'inputs_length': <tf.Tensor 'Placeholder_1:0' shape=(None,) dtype=int32>, 'signal': <tf.Tensor 'Placeholder_4:0' shape=(None, None, 1) dtype=float32>, 'predictions': <tf.Tensor 'Placeholder_2:0' shape=(None, None) dtype=int32>, 'predictions_length': <tf.Tensor 'Placeholder_3:0' shape=(None,) dtype=int32>}
the out put of encoder is =========== Tensor("contextnet/contextnet_encoder/contextnet_encoder_block_22/IdentityN:0", shape=(None, None, 320), dtype=float32)
inputs[predictions] Tensor("Placeholder_2:0", shape=(None, None), dtype=int32)

++++++++++++++++Inside Transducer Prediction ++++++++++++++++++
the inputs are ===== Tensor("Placeholder_2:0", shape=(None, None), dtype=int32)
the inputs are ========== Tensor("Placeholder_3:0", shape=(None,), dtype=int32)
the outputs after embed are ========== Tensor("Placehol

In [4]:
with tf.GradientTape(persistent=True) as tape:
    
#     batch_size = config.learning_config.running_config.batch_size
#     contextnet = ContextNet(**config.model_config, vocabulary_size=text_featurizer.num_classes)
#     contextnet.make(speech_featurizer.shape)
#     contextnet.load_weights("/Users/vaibhavsingh/Desktop/TensorFlowASR/examples/contextnet/checkpoint/model_trained_01.h5", by_name=True)  

    # contextnet.load_weights("model_all_re_cn_09.h5", by_name=True)

#     contextnet.summary(line_length=100)
    contextnet.add_featurizers(speech_featurizer, text_featurizer)
    optimizer = tf.keras.optimizers.Adam(
        TransformerSchedule(
            d_model=contextnet.dmodel,
            warmup_steps=config.learning_config.optimizer_config.pop("warmup_steps", 10000),
            max_lr=(0.05 / math.sqrt(contextnet.dmodel))
        ),
        **config.learning_config.optimizer_config
    )

    contextnet.compile(
        optimizer=optimizer,
        experimental_steps_per_execution=1,
        global_batch_size=1,
        blank=text_featurizer.blank
    )
    encoder = contextnet.layers[0]
    test_data_loader = test_dataset.create(batch_size)

    
    for i, j in test_data_loader:

        inputs = tf.Variable(i["inputs"])
        inputs_length = tf.Variable(i["inputs_length"])
        signal = tf.Variable(i["signal"])

        encoder_output = encoder.call_feature_output([inputs, inputs_length, signal])
        print("encoder output--------", encoder_output)
        individual_layer_output_list = encoder.feature_output
        print("individual output===========", individual_layer_output_list)
    
        #Basically this output is same as the input, will be used to check the grad with input, should be equal to 1
        out_1_layer = tf.Variable(individual_layer_output_list[0])
        #make this 
        norm_raw_output = tf.norm(encoder_output, axis=1)
        
#         final_node = tf.math.argmax(tf.squeeze(tf.reduce_sum(encoder_output, axis=1)))
#         print("fial_node====", final_node)
        k = tape.gradient(encoder_output, inputs)
        
#         print("-----xx", inputs.sh)
        print("k---", k)
        
        #Reseting these layers after processing.
        encoder.feature_output = []
       
        tape.reset()
        break
        
        
    


  opt = tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt)
Reading /Users/vaibhavsingh/Desktop/TensorFlowASR/scripts/Datasets/test-clean-sanity/transcripts.tsv ...

+++++++++++++inside tf_preprocess+++++++++++++++
indics are======== Tensor("args_2:0", shape=(), dtype=string)
signal is ======= Tensor("Reshape:0", shape=(None,), dtype=float32, device=/device:CPU:0)
features ======== Tensor("truediv_3:0", shape=(None, 80, 1), dtype=float32, device=/device:CPU:0)
input length is ========== Tensor("strided_slice_3:0", shape=(), dtype=int32, device=/device:CPU:0)
label is ======== Tensor("StringToNumber:0", shape=(None,), dtype=int32, device=/device:CPU:0)
label length is ======== Tensor("strided_slice_4:0", shape=(), dtype=int32, device=/device:CPU:0)
prediction is ==========  Tensor("concat_1:0", shape=(None,), dtype=int32, device=/device:CPU:0)
prediction_length is ======= Tensor("strided_slice_5:0", shape=(), dtype=int32, device=/device:CPU:0)
inside the call fx of encoder----

k--- tf.Tensor(
[[[[ 0.06954755]
   [-0.11481058]
   [ 0.07483   ]
   ...
   [-0.05168561]
   [-0.06301225]
   [-0.22830036]]

  [[-0.07394463]
   [ 0.08222591]
   [ 0.04261129]
   ...
   [ 0.12350222]
   [ 0.18509507]
   [ 0.12434705]]

  [[ 0.02821412]
   [ 0.01392338]
   [-0.0837923 ]
   ...
   [-0.17926748]
   [-0.05078284]
   [-0.36466584]]

  ...

  [[-0.00150448]
   [ 0.04333932]
   [-0.03819435]
   ...
   [-0.03101875]
   [-0.02542069]
   [-0.04937126]]

  [[ 0.04455832]
   [-0.026463  ]
   [-0.0298469 ]
   ...
   [ 0.11789368]
   [ 0.08691536]
   [ 0.18451943]]

  [[-0.03667189]
   [ 0.03476194]
   [-0.03532824]
   ...
   [-0.02227324]
   [-0.0136091 ]
   [ 0.02572925]]]], shape=(1, 608, 80, 1), dtype=float32)


In [5]:
for i, j in test_data_loader:
    print(i,j)
    break

{'inputs': <tf.Tensor: shape=(1, 608, 80, 1), dtype=float32, numpy=
array([[[[-0.88430405],
         [-1.0025831 ],
         [-1.8104411 ],
         ...,
         [-1.1646435 ],
         [-1.4017149 ],
         [-2.1446335 ]],

        [[-0.95217824],
         [-0.8431829 ],
         [-0.7029175 ],
         ...,
         [-0.9792209 ],
         [-1.6376293 ],
         [-2.191236  ]],

        [[-1.1578585 ],
         [-0.9471249 ],
         [-0.73311234],
         ...,
         [-1.1570454 ],
         [-1.768073  ],
         [-2.343823  ]],

        ...,

        [[-0.83737606],
         [-0.749652  ],
         [-0.6308468 ],
         ...,
         [-1.1891571 ],
         [-1.4152755 ],
         [-1.9534897 ]],

        [[-1.0136111 ],
         [-0.8318222 ],
         [-0.63500834],
         ...,
         [-1.0849377 ],
         [-1.2815615 ],
         [-2.2296257 ]],

        [[-0.91157675],
         [-0.7796618 ],
         [-0.61910915],
         ...,
         [-1.1070294 ],
        

In [6]:
with tf.GradientTape(persistent=True) as tape:
    
#     batch_size = config.learning_config.running_config.batch_size
#     contextnet = ContextNet(**config.model_config, vocabulary_size=text_featurizer.num_classes)
#     contextnet.make(speech_featurizer.shape)
#     contextnet.load_weights("/Users/vaibhavsingh/Desktop/TensorFlowASR/examples/contextnet/checkpoint/model_trained_01.h5", by_name=True)  

    # contextnet.load_weights("model_all_re_cn_09.h5", by_name=True)

#     contextnet.summary(line_length=100)
    contextnet.add_featurizers(speech_featurizer, text_featurizer)
    optimizer = tf.keras.optimizers.Adam(
        TransformerSchedule(
            d_model=contextnet.dmodel,
            warmup_steps=config.learning_config.optimizer_config.pop("warmup_steps", 10000),
            max_lr=(0.05 / math.sqrt(contextnet.dmodel))
        ),
        **config.learning_config.optimizer_config
    )

    contextnet.compile(
        optimizer=optimizer,
        experimental_steps_per_execution=1,
        global_batch_size=1,
        blank=text_featurizer.blank
    )
    
    

    
    for i, j in test_data_loader:

        output = contextnet(i)
        print("final output--------", output)
        
        k = tape.gradient(output, i)
        
#         print("-----xx", inputs.sh)
        print("k---", k)
        
        tape.reset()
        break
        
        

  opt = tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt)
================INSIDE TRANSDUCER=================
before going to the encoder================= {'inputs': <tf.Tensor: shape=(1, 608, 80, 1), dtype=float32, numpy=
array([[[[-0.88430405],
         [-1.0025831 ],
         [-1.8104411 ],
         ...,
         [-1.1646435 ],
         [-1.4017149 ],
         [-2.1446335 ]],

        [[-0.95217824],
         [-0.8431829 ],
         [-0.7029175 ],
         ...,
         [-0.9792209 ],
         [-1.6376293 ],
         [-2.191236  ]],

        [[-1.1578585 ],
         [-0.9471249 ],
         [-0.73311234],
         ...,
         [-1.1570454 ],
         [-1.768073  ],
         [-2.343823  ]],

        ...,

        [[-0.83737606],
         [-0.749652  ],
         [-0.6308468 ],
         ...,
         [-1.1891571 ],
         [-1.4152755 ],
         [-1.9534897 ]],

        [[-1.0136111 ],
         [-0.8318222 ],
         [-0.63500834],
         ...,
         [-1.0849377 ],
  

k--- {'inputs': None, 'inputs_length': None, 'signal': None, 'predictions': None, 'predictions_length': None}


In [8]:
print(test_dataset.total_steps)

6


In [11]:
results = contextnet.evaluate(test_data_loader)
    
    

================INSIDE TRANSDUCER=================
before going to the encoder================= {'inputs': <tf.Tensor 'IteratorGetNext:0' shape=(1, None, 80, 1) dtype=float32>, 'inputs_length': <tf.Tensor 'IteratorGetNext:1' shape=(1,) dtype=int32>, 'signal': <tf.Tensor 'IteratorGetNext:4' shape=(1, None, 1) dtype=float32>, 'predictions': <tf.Tensor 'IteratorGetNext:2' shape=(1, None) dtype=int32>, 'predictions_length': <tf.Tensor 'IteratorGetNext:3' shape=(1,) dtype=int32>}
the out put of encoder is =========== Tensor("contextnet/contextnet_encoder/contextnet_encoder_block_22/IdentityN:0", shape=(1, None, 320), dtype=float32)
inputs[predictions] Tensor("IteratorGetNext:2", shape=(1, None), dtype=int32)

++++++++++++++++Inside Transducer Prediction ++++++++++++++++++
the inputs are ===== Tensor("IteratorGetNext:2", shape=(1, None), dtype=int32)
the inputs are ========== Tensor("IteratorGetNext:3", shape=(1,), dtype=int32)
the outputs after embed are ========== Tensor("IteratorGetNext:3

In [12]:
results

19.823598861694336

In [13]:
v1 = tf.random.uniform(shape=(4,))

In [14]:
v1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.12264264, 0.10379314, 0.75350153, 0.5331385 ], dtype=float32)>

In [22]:
nrm = tf.norm(v1)
print(nrm)
ans = map(lambda i: i**2, v1)
k = sum(ans)
print(math.sqrt(k))
    

tf.Tensor(0.9369181, shape=(), dtype=float32)
0.9369180780626503


In [34]:
v2 = tf.convert_to_tensor([[3,4], [1,2]], dtype='float32')
print(v2)

tf.Tensor(
[[3. 4.]
 [1. 2.]], shape=(2, 2), dtype=float32)


In [35]:
tf.norm(v2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.477226>

In [82]:
model = contextnet.layers[0].trainable_variables
for i in model:
    print(i)
    print(i.name.split('/'))


<tf.Variable 'contextnet/contextnet_encoder/contextnet_encoder_block_0/contextnet_encoder_block_0_conv_module_0/contextnet_encoder_block_0_conv_module_0_bn/gamma:0' shape=(128,) dtype=float32, numpy=
array([0.8622457 , 0.96367335, 1.427973  , 0.91040725, 1.13594   ,
       1.2244726 , 0.9343247 , 0.9700279 , 0.8098883 , 1.0433266 ,
       0.8789854 , 1.2242229 , 0.90962285, 0.933949  , 1.0617172 ,
       1.0018609 , 1.0668114 , 0.9697842 , 0.8793499 , 1.1692476 ,
       1.0109953 , 0.936281  , 0.96965885, 0.9763931 , 0.9669873 ,
       0.96429545, 1.0561721 , 0.95920086, 1.0170506 , 0.9420409 ,
       1.3680396 , 0.8748591 , 1.001032  , 1.2988584 , 1.1161833 ,
       1.084274  , 1.1670814 , 0.95412624, 0.92089814, 1.0164925 ,
       1.0846757 , 0.9952453 , 0.9870674 , 0.8839013 , 1.0096214 ,
       0.86815965, 0.89147013, 1.0143049 , 1.090806  , 0.9848545 ,
       1.195078  , 1.0028483 , 0.92745405, 1.0772929 , 0.95554286,
       1.1251866 , 0.8853114 , 1.040742  , 0.9904603 , 1.010365

<tf.Variable 'contextnet/contextnet_encoder/contextnet_encoder_block_2/contextnet_encoder_block_2_conv_module_2/contextnet_encoder_block_2_conv_module_2_convDSC/depthwise_kernel:0' shape=(5, 1, 128, 1) dtype=float32, numpy=
array([[[[-2.62077358e-02],
         [ 9.87259438e-04],
         [ 1.85458735e-02],
         [-7.96842203e-02],
         [ 1.44171461e-01],
         [-2.57391520e-02],
         [-1.48946587e-02],
         [-1.58707257e-02],
         [ 4.94744852e-02],
         [-8.68055746e-02],
         [-7.01421499e-02],
         [ 6.80664647e-03],
         [-4.14571203e-02],
         [-4.18447554e-02],
         [-1.59779526e-02],
         [ 1.41561357e-02],
         [-7.33524933e-03],
         [ 5.89325465e-02],
         [-9.51959342e-02],
         [ 8.04150328e-02],
         [ 6.98436890e-03],
         [-7.91407749e-02],
         [-3.42825651e-02],
         [ 4.17104512e-02],
         [ 1.63426436e-02],
         [-4.10878025e-02],
         [ 1.04912147e-01],
         [-4.9975436

         [ 6.30389526e-02]]]], dtype=float32)>
['contextnet', 'contextnet_encoder', 'contextnet_encoder_block_4', 'contextnet_encoder_block_4_conv_module_1', 'contextnet_encoder_block_4_conv_module_1_convDSC', 'depthwise_kernel:0']
<tf.Variable 'contextnet/contextnet_encoder/contextnet_encoder_block_4/contextnet_encoder_block_4_conv_module_1/contextnet_encoder_block_4_conv_module_1_convDSC/bias:0' shape=(128,) dtype=float32, numpy=
array([-0.05677673,  0.01418129, -0.06086707, -0.00506693, -0.00814534,
       -0.07537086,  0.0869441 , -0.00467844,  0.04984479, -0.07300434,
       -0.00238425, -0.01963475,  0.01271483, -0.00960751,  0.00809247,
       -0.01789391, -0.0713252 ,  0.01528142,  0.00782435, -0.03052511,
       -0.00794335,  0.02389492,  0.04513361, -0.02658566,  0.04674147,
        0.06255535,  0.01272214, -0.02965039, -0.01836153,  0.0361743 ,
        0.00486084,  0.0013038 , -0.00979919,  0.11876748,  0.04234213,
       -0.02398352,  0.07178195,  0.00330974, -0.07967881, -

<tf.Variable 'contextnet/contextnet_encoder/contextnet_encoder_block_6/contextnet_encoder_block_6_conv_module_2/contextnet_encoder_block_6_conv_module_2_convDSC/depthwise_kernel:0' shape=(5, 1, 128, 1) dtype=float32, numpy=
array([[[[-1.07711010e-01],
         [ 6.47272244e-02],
         [ 8.76452215e-03],
         [-2.77433172e-02],
         [-1.46541167e-02],
         [ 4.15974632e-02],
         [-6.22694716e-02],
         [-6.54887557e-02],
         [ 8.89154375e-02],
         [-6.79700694e-04],
         [-1.67168513e-01],
         [-4.81253229e-02],
         [ 6.47756979e-02],
         [ 1.93772335e-02],
         [ 2.87218392e-02],
         [-8.60031322e-02],
         [-6.70344848e-03],
         [-6.75036982e-02],
         [ 5.62020391e-02],
         [-6.58892561e-03],
         [ 1.01795562e-01],
         [-6.49911165e-02],
         [-7.09405243e-02],
         [ 5.34147024e-03],
         [-9.63698421e-03],
         [ 4.01326492e-02],
         [-1.82357319e-02],
         [-7.8824095

         [-0.08639607]]]], dtype=float32)>
['contextnet', 'contextnet_encoder', 'contextnet_encoder_block_8', 'contextnet_encoder_block_8_conv_module_3', 'contextnet_encoder_block_8_conv_module_3_convDSC', 'depthwise_kernel:0']
<tf.Variable 'contextnet/contextnet_encoder/contextnet_encoder_block_8/contextnet_encoder_block_8_conv_module_3/contextnet_encoder_block_8_conv_module_3_convDSC/bias:0' shape=(128,) dtype=float32, numpy=
array([ 3.91628854e-02,  7.78797606e-04,  1.64123271e-02, -4.27665077e-02,
        4.17757872e-03,  6.66178614e-02, -1.45899045e-04,  2.51982063e-02,
       -7.86136016e-02, -3.64922956e-02,  1.78383719e-02, -3.39464433e-02,
        7.47214556e-02,  3.17158625e-02, -1.30506093e-02,  5.79962432e-02,
        1.64559148e-02, -1.97700821e-02, -4.24609557e-02,  6.94373474e-02,
        7.14508891e-02, -1.04029745e-01, -1.27659962e-02,  2.65108924e-02,
       -3.60454321e-02,  5.11361584e-02,  1.29658310e-02, -7.14686438e-02,
       -1.17460461e-02, -2.91272569e-02, -9

       1.0393833 ], dtype=float32)>
['contextnet', 'contextnet_encoder', 'contextnet_encoder_block_11', 'contextnet_encoder_block_11_conv_module_0', 'contextnet_encoder_block_11_conv_module_0_bn', 'gamma:0']
<tf.Variable 'contextnet/contextnet_encoder/contextnet_encoder_block_11/contextnet_encoder_block_11_conv_module_0/contextnet_encoder_block_11_conv_module_0_bn/beta:0' shape=(256,) dtype=float32, numpy=
array([-0.01968173, -0.00576883,  0.05091904,  0.05734472, -0.03394551,
       -0.01448888, -0.01548882,  0.09923509,  0.01305841, -0.01178792,
        0.05017395,  0.06369822,  0.00897614, -0.01922986,  0.00917963,
        0.027366  , -0.0147133 , -0.07324043, -0.00807318, -0.03242192,
       -0.0015908 ,  0.00545531,  0.04320488, -0.02708655,  0.05087296,
       -0.024277  , -0.05422058,  0.01675156, -0.04149216,  0.02786311,
       -0.0053902 ,  0.06735229, -0.04561943,  0.08797304,  0.00940903,
        0.00852489, -0.06027379,  0.03798962,  0.06725773,  0.09627637,
        0.0347

        0.00492952,  0.01986846], dtype=float32)>
['contextnet', 'contextnet_encoder', 'contextnet_encoder_block_13', 'contextnet_encoder_block_13_se', 'contextnet_encoder_block_13_se_fc1', 'bias:0']
<tf.Variable 'contextnet/contextnet_encoder/contextnet_encoder_block_13/contextnet_encoder_block_13_se/contextnet_encoder_block_13_se_fc2/kernel:0' shape=(32, 256) dtype=float32, numpy=
array([[-0.08808153, -0.18409155, -0.07281627, ..., -0.12800238,
        -0.0562172 , -0.1848032 ],
       [-0.06261867, -0.0760371 , -0.0610372 , ...,  0.09009884,
         0.01838855, -0.0443522 ],
       [-0.05353883,  0.13334742, -0.15472059, ..., -0.02805254,
         0.0275854 ,  0.08507928],
       ...,
       [ 0.00548979, -0.13555849, -0.22938927, ...,  0.10084739,
        -0.06812979,  0.04398328],
       [ 0.02667247,  0.0601394 , -0.04505518, ...,  0.05610093,
        -0.08741636, -0.05262168],
       [ 0.03689108, -0.05767768,  0.17613362, ...,  0.02859786,
         0.00912659,  0.0352856 ]], d

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [15]:
############################### Testing out a simple subclassing model to mimic pytorch model############################

In [1]:
class SimpleModel(tf.keras.Model):
    def __init__(self, **kwargs):
        super(SimpleModel, self).__init__(**kwargs)
        self.conv1 = tf.keras.layers.Conv2D(filters = 6, kernel_size=5)
        self.pool = tf.keras.layers.MaxPool2D(pool_size=(2,2))
        self.conv2 = tf.keras.layers.Conv2D(filters = 16, kernel_size=5)
        self.fc1 = tf.keras.layers.Dense(120)
        self.fc2 = tf.keras.layers.Dense(84)
        self.fc3 = tf.keras.layers.Dense(10)
        
        self.flatten = tf.keras.layers.Flatten()
    
    def call(self, input_tensor, training=False):
        x = self.pool(tf.nn.relu(self.conv1(input_tensor)))
        x = self.pool(tf.nn.relu(self.conv2(x)))
        x = self.flatten(x)
        x = tf.nn.relu(self.fc1(x))
        x = tf.nn.relu(self.fc2(x))
        x = self.fc3(x)
        return x

NameError: name 'tf' is not defined

In [41]:
output = SimpleModel()

In [42]:
input_t = tf.random.uniform(shape=(1,32,32,3))
print(input_t.shape)

(1, 32, 32, 3)


In [43]:
m = output(input_t)

In [77]:
for i in output.trainable_var:
    
#     print(i.name)
    
    if "conv" in i.name or "dense" in i.name:
        print(i.bias)
#         print(1)
#         print(i.bias)
    
        

<tf.Variable 'simple_model_5/conv2d_8/bias:0' shape=(6,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0.], dtype=float32)>
<tf.Variable 'simple_model_5/conv2d_9/bias:0' shape=(16,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>
<tf.Variable 'simple_model_5/dense_9/bias:0' shape=(120,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)>
<tf.Variable 'simple_model_5/dense_10/bias:0' shape=(84,) dtype=flo

In [25]:
# print(adc[0])
# print(inputs)
nb = np.array([1,2,3,4])
nb = tf.convert_to_tensor(nb)
print(nb)
m = tf.math.argmax(nb)
print(m)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)


In [20]:
print(inputs)

<tf.Variable 'Variable:0' shape=(1, 608, 80, 1) dtype=float32, numpy=
array([[[[-0.88430405],
         [-1.0025831 ],
         [-1.8104411 ],
         ...,
         [-1.1646435 ],
         [-1.4017149 ],
         [-2.1446335 ]],

        [[-0.95217824],
         [-0.8431829 ],
         [-0.7029175 ],
         ...,
         [-0.9792209 ],
         [-1.6376293 ],
         [-2.191236  ]],

        [[-1.1578585 ],
         [-0.9471249 ],
         [-0.73311234],
         ...,
         [-1.1570454 ],
         [-1.768073  ],
         [-2.343823  ]],

        ...,

        [[-0.83737606],
         [-0.749652  ],
         [-0.6308468 ],
         ...,
         [-1.1891571 ],
         [-1.4152755 ],
         [-1.9534897 ]],

        [[-1.0136111 ],
         [-0.8318222 ],
         [-0.63500834],
         ...,
         [-1.0849377 ],
         [-1.2815615 ],
         [-2.2296257 ]],

        [[-0.91157675],
         [-0.7796618 ],
         [-0.61910915],
         ...,
         [-1.1070294 ],
      

In [231]:
for i, j in test_data_loader:
    print(i)
    break

{'inputs': <tf.Tensor: shape=(1, 608, 80, 1), dtype=float32, numpy=
array([[[[-0.88430405],
         [-1.0025831 ],
         [-1.8104411 ],
         ...,
         [-1.1646435 ],
         [-1.4017149 ],
         [-2.1446335 ]],

        [[-0.95217824],
         [-0.8431829 ],
         [-0.7029175 ],
         ...,
         [-0.9792209 ],
         [-1.6376293 ],
         [-2.191236  ]],

        [[-1.1578585 ],
         [-0.9471249 ],
         [-0.73311234],
         ...,
         [-1.1570454 ],
         [-1.768073  ],
         [-2.343823  ]],

        ...,

        [[-0.83737606],
         [-0.749652  ],
         [-0.6308468 ],
         ...,
         [-1.1891571 ],
         [-1.4152755 ],
         [-1.9534897 ]],

        [[-1.0136111 ],
         [-0.8318222 ],
         [-0.63500834],
         ...,
         [-1.0849377 ],
         [-1.2815615 ],
         [-2.2296257 ]],

        [[-0.91157675],
         [-0.7796618 ],
         [-0.61910915],
         ...,
         [-1.1070294 ],
        

In [22]:
model=Sequential()
model.add(Dense(40, activation='softmax',input_dim=12))
model.add(Dense(60, activation='relu'))
model.add(Dense(units=6, activation='relu'))
model.add(Dense(units=3, activation='relu'))

opt=tf.keras.optimizers.Adam(lr=0.001)


x=np.random.random(12).reshape(-1,12)
with tf.GradientTape(persistent=True) as tape:
    y = tf.convert_to_tensor(x)
    tape.watch(y)
    print(y.shape)
    x2 = model([y])
    print(x2.shape, x2)
    loss = -tf.reduce_mean(x2)
    print(loss)
    
grad = tape.gradient(x2, y)
print(grad)
# opt.apply_gradients(zip(grad, model.trainable_variables))

(1, 12)
(1, 3) tf.Tensor([[0.01567648 0.         0.        ]], shape=(1, 3), dtype=float32)
tf.Tensor(-0.005225494, shape=(), dtype=float32)
tf.Tensor(
[[-0.0013156  -0.00511432  0.00331792  0.00055893  0.00248314  0.00168554
   0.00069028  0.00292185 -0.00059704 -0.00135096  0.0026982  -0.00297132]], shape=(1, 12), dtype=float64)


In [185]:
tape.gradient(x2, y)

<tf.Tensor: shape=(1, 12), dtype=float64, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])>

In [4]:
optimizer = tf.keras.optimizers.Adam(
        TransformerSchedule(
            d_model=contextnet.dmodel,
            warmup_steps=config.learning_config.optimizer_config.pop("warmup_steps", 10000),
            max_lr=(0.05 / math.sqrt(contextnet.dmodel))
        ),
        **config.learning_config.optimizer_config
    )

contextnet.compile(
    optimizer=optimizer,
    experimental_steps_per_execution=1,
    global_batch_size=1,
    blank=text_featurizer.blank
)

callbacks = [
    tf.keras.callbacks.ModelCheckpoint(**config.learning_config.running_config.checkpoint),
    tf.keras.callbacks.experimental.BackupAndRestore(config.learning_config.running_config.states_dir),
    tf.keras.callbacks.TensorBoard(**config.learning_config.running_config.tensorboard)
]

batch_size = config.learning_config.running_config.batch_size
# eval_data_loader = eval_dataset.create(batch_size)
test_data_loader = test_dataset.create(batch_size)
# value = contextnet.evaluate(eval_data_loader, batch_size=batch_size, callbacks=callbacks)
# print(contextnet.metrics_names,"--------------")
# print(value,"--------------")

def get_weights(net):
    return net.layers[0].get_weights()

  opt = tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt)
Reading /Users/vaibhavsingh/Desktop/TensorFlowASR/scripts/Datasets/test-clean-sanity/transcripts.tsv ...


In [5]:
import os
import io
import abc
import math
import numpy as np
import librosa
import soundfile as sf
import tensorflow as tf
import tensorflow_io as tfio

def load_and_convert_to_wav(path: str) -> tf.Tensor:
    wave, rate = librosa.load(os.path.expanduser(path), sr=None, mono=True)
    print("----------------------------------------")
    print(wave, rate)
    return tf.audio.encode_wav(tf.expand_dims(wave, axis=-1), sample_rate=rate)


def fn(path: bytes):
    return load_and_convert_to_wav(path).numpy()


In [7]:
file = "/Users/vaibhavsingh/Desktop/TensorFlowASR/scripts/Datasets/train-clean-100/LibriSpeech/train-clean-100/26/495/26-495-0000.flac"
# file2 = "/Users/vaibhavsingh/Desktop/TensorFlowASR/scripts/Datasets/train-clean-100/LibriSpeech/train-clean-100/19/198/19-198-0002.flac"


In [22]:
audio = fn(file)
# audio2 = fn(file2)

----------------------------------------
[ 0.00360107  0.00384521 -0.00436401 ...  0.00106812  0.00180054
  0.00146484] 16000


In [9]:
wave, rate = tf.audio.decode_wav(audio, desired_channels=1, desired_samples=-1)
# wave2, rate2 = tf.audio.decode_wav(audio2, desired_channels=1, desired_samples=-1)

In [10]:
print(wave, rate)
# print(wave2, rate2)

tf.Tensor(
[[ 0.00360107]
 [ 0.00384521]
 [-0.00436401]
 ...
 [ 0.00106812]
 [ 0.00180054]
 [ 0.00146484]], shape=(154800, 1), dtype=float32) tf.Tensor(16000, shape=(), dtype=int32)


In [16]:
sample_rate=16000
resampled = tfio.audio.resample(wave, rate_in=tf.cast(rate, dtype=tf.int64), rate_out=sample_rate)
# resampled2 = tfio.audio.resample(wave2, rate_in=tf.cast(rate2, dtype=tf.int64), rate_out=sample_rate)
print(resampled)
# print(resampled2)

tf.Tensor(
[[ 2.08347650e-08]
 [-6.07784827e-08]
 [ 1.01691015e-07]
 ...
 [ 1.85308512e-03]
 [ 1.44618121e-03]
 [ 1.35750882e-03]], shape=(154800, 1), dtype=float32)


In [15]:
signal = tf.reshape(resampled, shape=[-1])
# signal2 = tf.reshape(resampled2, shape=[-1])
print(signal, signal.shape)
# print(signal2)

tf.Tensor(
[ 2.08347650e-08 -6.07784827e-08  1.01691015e-07 ...  1.85308512e-03
  1.44618121e-03  1.35750882e-03], shape=(154800,), dtype=float32) (154800,)


In [17]:
from tensorflow_asr.augmentations.augmentation import Augmentation

In [18]:
features = speech_featurizer.tf_extract(signal)

In [19]:
print(features)


tf.Tensor(
[[[-1.1075792 ]
  [-1.1152742 ]
  [-1.14224   ]
  ...
  [ 0.13340296]
  [-0.13371825]
  [-0.07032747]]

 [[-1.1568089 ]
  [-1.0485059 ]
  [-0.9180523 ]
  ...
  [ 0.18181649]
  [-0.13856299]
  [-0.07530545]]

 [[-1.2461052 ]
  [-1.1882193 ]
  [-1.1071631 ]
  ...
  [ 0.19731618]
  [-0.26973835]
  [-0.41382822]]

 ...

 [[-1.262011  ]
  [-1.0573418 ]
  [-0.8686971 ]
  ...
  [-0.8124411 ]
  [-1.2648714 ]
  [-1.6648448 ]]

 [[-1.3339529 ]
  [-1.1959482 ]
  [-1.0437148 ]
  ...
  [-0.88766176]
  [-1.3892792 ]
  [-1.6648448 ]]

 [[-1.0808375 ]
  [-1.0053201 ]
  [-0.90478504]
  ...
  [-0.922016  ]
  [-1.1421442 ]
  [-1.5924511 ]]], shape=(968, 80, 1), dtype=float32)


In [20]:
input_length = tf.cast(tf.shape(features)[0], tf.int32)
print(input_length)

tf.Tensor(968, shape=(), dtype=int32)


In [23]:
signal = tf.expand_dims(signal, axis=-1)
print(signal)

tf.Tensor(
[[ 2.08347650e-08]
 [-6.07784827e-08]
 [ 1.01691015e-07]
 ...
 [ 1.85308512e-03]
 [ 1.44618121e-03]
 [ 1.35750882e-03]], shape=(154800, 1), dtype=float32)


In [33]:
m = np.random.rand(6,3,4)

In [34]:
m.shape

(6, 3, 4)

k=tf.data.Dataset.from_tensor_slices(m)


In [39]:
k=tf.data.Dataset.from_tensor_slices(m)

In [40]:
obj = ASRSliceDataset(
        speech_featurizer=speech_featurizer,
        text_featurizer=text_featurizer,
        **vars(config.learning_config.test_dataset_config)
    )

In [41]:
obj.read_entries()

Reading /Users/vaibhavsingh/Desktop/TensorFlowASR/scripts/Datasets/test-clean-sanity/transcripts.tsv ...


In [48]:
data = tf.data.Dataset.from_tensor_slices(obj.entries)

In [50]:
obj.entries

array([['/Users/vaibhavsingh/Desktop/TensorFlowASR/scripts/Datasets/test-clean/LibriSpeech/test-clean/61/70970/61-70970-0000.flac',
        '6.075',
        '26 16 22 15 8 1 7 10 21 27 16 16 21 9 1 9 2 5 1 3 6 6 15 1 4 16 14 14 2 15 5 6 5 1 21 16 1 9 10 20 1 14 16 21 9 6 19 28 20 1 4 9 2 14 3 6 19 1 20 16 1 20 16 16 15 1 2 20 1 9 6 1 9 2 5 1 4 16 14 6 1 16 22 21 1 7 19 16 14 1 9 10 20 1 4 16 15 23 6 19 20 6 1 24 10 21 9 1 21 9 6 1 20 18 22 10 19 6'],
       ['/Users/vaibhavsingh/Desktop/TensorFlowASR/scripts/Datasets/test-clean/LibriSpeech/test-clean/61/70968/61-70968-0000.flac',
        '4.905',
        '9 6 1 3 6 8 2 15 1 2 1 4 16 15 7 22 20 6 5 1 4 16 14 17 13 2 10 15 21 1 2 8 2 10 15 20 21 1 21 9 6 1 24 10 27 2 19 5 1 24 9 16 1 9 2 5 1 23 2 15 10 20 9 6 5 1 3 6 9 10 15 5 1 21 9 6 1 4 22 19 21 2 10 15 1 16 15 1 21 9 6 1 13 6 7 21'],
       ['/Users/vaibhavsingh/Desktop/TensorFlowASR/scripts/Datasets/test-clean/LibriSpeech/test-clean/5639/40744/5639-40744-0000.flac',
        '15.77',

In [50]:

    contextnet.load_weights("/Users/vaibhavsingh/Desktop/TensorFlowASR/examples/contextnet/checkpoint/model_trained_01.h5", by_name=True)  
    encoder = contextnet.layers[0]
    print(len(encoder.layers))
    inputs = tf.random.uniform((1,87,80,1), 0, 1, tf.float32)
    inputs_length = tf.random.uniform(shape=(1,))
    predictions = tf.random.uniform(shape=(1,))
    predictions_length = tf.random.uniform(shape=(1,))
    signal = tf.random.uniform(shape = tf.TensorShape((1, 200, 1)))

    abcd = encoder.call_feature_output([inputs, inputs_length, signal])
    adc = encoder.feature_output
    nrm = tf.norm(abcd, axis=1)
    final_node = max(tf.reduce_sum(nrm, axis=0))
    
   



24
inside the call fx of encoder------------------------------ [<tf.Tensor: shape=(1, 87, 80, 1), dtype=float32, numpy=
array([[[[0.36795104],
         [0.40905368],
         [0.42036116],
         ...,
         [0.31243265],
         [0.57353616],
         [0.47037077]],

        [[0.5778127 ],
         [0.6736921 ],
         [0.86984193],
         ...,
         [0.31472683],
         [0.24778426],
         [0.95389485]],

        [[0.47671986],
         [0.36146486],
         [0.5852151 ],
         ...,
         [0.56436086],
         [0.4205544 ],
         [0.25291753]],

        ...,

        [[0.8110529 ],
         [0.37920868],
         [0.02186537],
         ...,
         [0.51123893],
         [0.5723038 ],
         [0.8954637 ]],

        [[0.5424657 ],
         [0.5352715 ],
         [0.9362117 ],
         ...,
         [0.9525564 ],
         [0.24963415],
         [0.17245781]],

        [[0.934829  ],
         [0.04063737],
         [0.6472746 ],
         ...,
         [0.7

Inside convBlock======== tf.Tensor(
[[[ 4.6349182e-06  2.2082093e-08 -2.5364334e-05 ...  2.6263429e-05
    3.1737534e-06 -1.9600342e-05]
  [ 4.6180576e-06  2.8544636e-07 -2.5249819e-05 ...  2.6321755e-05
    3.0860006e-06 -1.9632751e-05]
  [ 4.6449577e-06  2.0806698e-07 -2.5469633e-05 ...  2.6346695e-05
    3.1637264e-06 -1.9656922e-05]
  ...
  [ 4.6429432e-06  2.1128501e-07 -2.5476833e-05 ...  2.6347851e-05
    3.1642983e-06 -1.9666220e-05]
  [ 4.5993797e-06  5.0021919e-07 -2.6327793e-05 ...  2.6346830e-05
    3.2845962e-06 -1.9653342e-05]
  [ 4.6491464e-06  5.4647330e-07 -2.7430542e-05 ...  2.6336518e-05
    3.1655488e-06 -1.9634546e-05]]], shape=(1, 11, 256), dtype=float32)

Inside convBlock======== tf.Tensor(
[[[ 9.5614387e-06  2.4962592e-05  4.7987178e-06 ... -4.3186128e-07
    1.2132849e-06 -1.7407492e-06]
  [ 9.3783738e-06  2.4565237e-05  4.8422658e-06 ... -3.5883679e-07
    1.0737159e-06 -1.7670487e-06]
  [ 9.4059706e-06  2.4302488e-05  4.8252186e-06 ... -4.1609039e-07
    1.02

In [51]:
print(final_node)

tf.Tensor(1.2962365e-05, shape=(), dtype=float32)


In [52]:
inp = tf.random.normal((1,87,80,1), 0, 1, tf.float32)
inp.shape
k = tf.random.normal(shape=(1,))
k.shape

TensorShape([1])

In [57]:
k = tape.gradient(final_node, )

In [58]:
print(k)

None


In [16]:
# d_norm1_tf = tf.norm(tf.reshape(random_vector, (random_vector.shape[0], -1)), axis=1, keepdims=True)[:, :, None]


RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead.

In [ ]:
# tensor= (bs*30*320)
# our features = 30(None)
# 1) output = tf.norm(tensor, axis=1, l2)
# 2) tf.max(tf.sum(output, axis=0))

# This basically gives us the most activated node, reduce it in 1 line [tf.max(tf.sum(tf.norm(tensor, axis=1, l2), axis=0))]


In [92]:
for l in encoder:
    print(l)
    try:
        print(l.convs)
        for k in l.convs:
            print("yo")
            print(k)
    except Exception as e:
        print("error", e)


TypeError: 'ContextNetEncoder' object is not iterable